language: c
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev
    - ca-certificates
    - software-properties-common 
    - python-software-properties
    - gnupg-curl

compiler:
  - gcc
  # - clang

env:
  - PG_VERSION=9.6
  - PG_VERSION=10

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y remove --purge postgresql-9.6
  - sudo apt-get -y autoremove
  - apt-key adv --fetch-keys https://www.postgresql.org/media/keys/ACCC4CF8.asc
  - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main $PG_VERSION"    
  - sudo apt-get update
  - sudo apt-get -y install postgresql-$PG_VERSION postgresql-server-dev-$PG_VERSION
  # - echo "local all postgres  trust" | sudo tee /etc/postgresql/$PG_VERSION/main/pg_hba.conf
  - sudo cat /etc/postgresql/$PG_VERSION/main/pg_hba.conf
  - sudo cat /etc/postgresql/$PG_VERSION/main/postgresql.conf
  - sudo /etc/init.d/postgresql start


script:
  - env
  - make
  - sudo make install
  - PGUSER=postgres PGPORT=5433 make installcheck || (cat regression.diffs && /bin/false)

