language: c
dist: trusty
sudo: required

addons:
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev

compiler:
  - gcc
  - clang

env:
  - PG_VERSION=9.6
  - PG_VERSION=10  

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y remove --purge postgresql-9.6
  - sudo apt-get -y remove --purge postgresql-10
  - sudo apt-get -y remove --purge postgresql-11
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PG_VERSION" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-$PG_VERSION postgresql-server-dev-$PG_VERSION
  - sudo /etc/init.d/postgresql-$PG_VERSION start
  # - sudo -u postgres /usr/lib/postgresql/$PG_VERSION/bin/pg_ctl start --pgdata=/var/lib/postgresql/$PG_VERSION/main -o "-c config_file=/etc/postgresql/$PG_VERSION/main/postgresql.conf" --log=/tmp/postgres.log

script:
  - env
  - make
  - sudo make install
  - PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)

