language: c

sudo: required

dist: trusty

addons:
  postgresql: "9.6"
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev

compiler:
  - gcc
  - clang

script:
  - make
  - sudo make install
  - make installcheck

