language: c

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - curl
    - libcurl4-gnutls-dev

compiler:
  - gcc
  - clang

before_script:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y remove --purge postgresql-9.5
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.6" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.6 postgresql-server-dev-9.6
  - sudo /etc/init.d/postgresql stop
  - sudo -u postgres /usr/lib/postgresql/9.5/bin/pg_ctl --pgdata=/var/lib/postgresql/9.5/main -o "-c config_file=/etc/postgresql/9.3/main/postgresql.conf" --log=/tmp/postgres.log

script:
  - env
  - make
  - sudo make install
  - PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)

