# GitHub Actions for PostGIS
#
# Paul Ramsey <pramsey at cleverelephant dot ca>

name: "CI"
on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    env:
      PG_VERSION: 14

    steps:

    - name: 'Check Out'
      uses: actions/checkout@v2

    - name: 'Install'
      run: |
        sudo apt-get -y install libcurl4-gnutls-dev postgresql-server-dev-$PG_VERSION
        sudo systemctl start postgresql.service

    - name: 'Build & Test'
      run: |
        export PATH=/usr/lib/postgresql/$PG_VERSION/bin/:$PATH
        make
        sudo make install
        PGUSER=postgres make installcheck || (cat regression.diffs && /bin/false)
